/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiV1StatusRouteImport } from './routes/api/v1/status'
import { Route as ApiV1ToolsRouteImport } from './routes/api/v1/tools'
import { Route as ApiV1ToolsExecuteRouteImport } from './routes/api/v1/tools.execute'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StatusRoute = ApiV1StatusRouteImport.update({
  id: '/api/v1/status',
  path: '/api/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ToolsRoute = ApiV1ToolsRouteImport.update({
  id: '/api/v1/tools',
  path: '/api/v1/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ToolsExecuteRoute = ApiV1ToolsExecuteRouteImport.update({
  id: '/execute',
  path: '/execute',
  getParentRoute: () => ApiV1ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/v1/status': typeof ApiV1StatusRoute
  '/api/v1/tools': typeof ApiV1ToolsRouteWithChildren
  '/api/v1/tools/execute': typeof ApiV1ToolsExecuteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/v1/status': typeof ApiV1StatusRoute
  '/api/v1/tools': typeof ApiV1ToolsRouteWithChildren
  '/api/v1/tools/execute': typeof ApiV1ToolsExecuteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/v1/status': typeof ApiV1StatusRoute
  '/api/v1/tools': typeof ApiV1ToolsRouteWithChildren
  '/api/v1/tools/execute': typeof ApiV1ToolsExecuteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/v1/status'
    | '/api/v1/tools'
    | '/api/v1/tools/execute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/v1/status'
    | '/api/v1/tools'
    | '/api/v1/tools/execute'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/v1/status'
    | '/api/v1/tools'
    | '/api/v1/tools/execute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiV1StatusRoute: typeof ApiV1StatusRoute
  ApiV1ToolsRoute: typeof ApiV1ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/status': {
      id: '/api/v1/status'
      path: '/api/v1/status'
      fullPath: '/api/v1/status'
      preLoaderRoute: typeof ApiV1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tools': {
      id: '/api/v1/tools'
      path: '/api/v1/tools'
      fullPath: '/api/v1/tools'
      preLoaderRoute: typeof ApiV1ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tools/execute': {
      id: '/api/v1/tools/execute'
      path: '/execute'
      fullPath: '/api/v1/tools/execute'
      preLoaderRoute: typeof ApiV1ToolsExecuteRouteImport
      parentRoute: typeof ApiV1ToolsRoute
    }
  }
}

interface ApiV1ToolsRouteChildren {
  ApiV1ToolsExecuteRoute: typeof ApiV1ToolsExecuteRoute
}

const ApiV1ToolsRouteChildren: ApiV1ToolsRouteChildren = {
  ApiV1ToolsExecuteRoute: ApiV1ToolsExecuteRoute,
}

const ApiV1ToolsRouteWithChildren = ApiV1ToolsRoute._addFileChildren(
  ApiV1ToolsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiV1StatusRoute: ApiV1StatusRoute,
  ApiV1ToolsRoute: ApiV1ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
